### ISSUE TITLE
Memory efficiency 

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/bulletproofs-plus#25]
It seems that the BP plus process has a lot of inefficient code in it and can use some cleanup. 
An example of this is the following:
```rust
        // Prepare for inner product
        let mut a_li_1 = Vec::with_capacity(a_li.len());
        for item in a_li {
            a_li_1.push(item - z);
        }
```
After this, the vec `a_li` is not used again, and only `a_li_1` is used. We can just in place replace them. 

The same can be said of `a_ri` .

The vector's `hi_base` and `gi_base` are copied multiple times where we can only borrow.

**Comment by AaronFeickert** [comment]
This [precomputation PR](https://github.com/tari-project/bulletproofs-plus/pull/19) does some cleanup in this direction.
