### ISSUE TITLE
Bump curve library version

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/bulletproofs-plus#39]
A [recent PR](https://github.com/tari-project/bulletproofs-plus/pull/38) updates several dependencies for better hardware library support, including the [curve library](https://github.com/tari-project/curve25519-dalek/pull/4). Now that a non-release-candidate version [has been issued](https://github.com/tari-project/curve25519-dalek/releases/tag/v4.0.3), it should be used here for consistency.

**Comment by hansieodendaal** [comment]
I think we can close this one as per https://github.com/tari-project/curve25519-dalek/pull/4

**Comment by AaronFeickert** [comment]
Not quite. There's now a [crates.io version bump](https://crates.io/crates/tari-curve25519-dalek/4.0.3) that should be referenced instead of the repository tag. This maintains consistency with other direct uses of crates in the ecosystem.
