### ISSUE TITLE
Update proof deserialization for clarity and safety

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/bulletproofs-plus#65]
Range proof [deserialization](https://github.com/tari-project/bulletproofs-plus/blob/d9d0cc9063f85684179908569227dda251981751/src/range_proof.rs#L832-L894) is fairly complex, as it uses a custom byte parsing. It also lacks documentation that makes its intent clear, and relies on several magic numbers.

There are a few improvements that would be welcome:
- Adding documentation and comments for clarity of intent and design
- Reducing reliance on magic numbers
- Moving from slice indexing to iterators (or other safe methods) to avoid the risk of panics and be more idiomatic
- Considering the use of more standard serialization implementations like [Borsh](https://borsh.io/), if reasonable given space efficiency
- Including fuzz testing to catch missing checks or edge cases

It's worth noting that the custom serialization is essentially optimal, as it infers the length of inner-product folding vectors and uses a small encoding of extension degree to define the length of a corresponding vector. The use of any other more standard/general serialization would likely increase the overall proof size by at least a dozen or so bytes due to vector length encoding.

**Comment by hansieodendaal** [comment]
Nice write-up. I agreed with all except _the use of more standard serialization implementations due to those not being optimal in size. We went to a lot of trouble to save `(96 - (16 + 8))` bytes, with those savings currently  `(96 - (16 + 8 + 32))` bytes.

**Comment by AaronFeickert** [comment]
Another useful refactoring would be to switch from compressed to uncompressed points in the proof struct, and only handle compression and decompression in the serialization functions. This seems much cleaner and idiomatic to me, since right now the prover and verifier need to know about compression.
